spring:
  data:
    mongodb:
      host: localhost
      database: book_db
  shell:
    interactive:
      enabled: true

mongock:
  migration-scan-package:
    - ru.otus.hw.migration
  enabled: true
  runner-type: initializingbean
  mongo-db:
    write-concern:
      journal: false
    read-concern: local

logging:
  level:
    org:
      springframework:
        data:
          mongodb:
            core:
              MongoTemplate: DEBUG