spring:
  data:
    mongodb:
      host: localhost
      database: book_db
  shell:
    interactive:
      enabled: true

mongock:
  migration-scan-package:
    - ru.otus.hw.migration
  enabled: true
  runner-type: initializingbean

logging:
  level:
    org:
      springframework:
        data:
          mongodb:
            core:
              MongoTemplate: DEBUG