spring:
  data:
    mongodb:
      host: localhost
      database: book_db
    rest:
      basePath: /datarest
  jmx:
    enabled: true
mongock:
  migration-scan-package:
    - ru.otus.hw.migration
  enabled: true
  runner-type: initializingbean
  mongo-db:
    write-concern:
      journal: false
    read-concern: local

resilience4j.circuitbreaker:
  configs:
    default:
      slidingWindowSize: 50

logging:
  level:
    ROOT: info
    org:
      springframework:
        data:
          mongodb:
            core:
              MongoTemplate: DEBUG

management:
  endpoints:
    web:
      exposure:
        include:
          - metrics
          - health
          - logfile
  endpoint:
    health:
      show-details: always
    logfile:
      external-file: log/spring-boot-logger.log
app:
  timeoutDuration: 5