spring:
  messages:
    baseName: messages
    encoding: UTF-8
    # Не дает свалиться в системную локаль если не найден файл для переданной в MessageSource
    # Если false то будут браться сообщения из дефолтного файла, если true, то из файла соответствующего системной локали
    fallbackToSystemLocale: false
  shell:
    interactive:
      enabled: true
    script:
      enabled: true
test:
  rightAnswersCountToPass: 3
  possibleLocales:
  - ru-RU
  - en-US
  locale: ru-RU
#  locale: en-US
  fileNameByLocaleTag:
    ru-RU: questions_ru.csv
    en-US: questions.csv