spring:
  batch:
    job:
      enabled: false

  data:
    mongodb:
      host: localhost
      database: book_db

  shell:
    interactive:
      enabled: true
    noninteractive:
      enabled: false
    command:
      version:
        enabled: false

  datasource:
    url: jdbc:h2:mem:maindb
    driverClassName: org.h2.Driver
    username: sa
    password:
  h2:
    console:
      path: /h2-console
      settings:
        web-allow-others: true
  flyway:
    enabled: true
    locations: classpath:db/migration
  jpa:
    generate-ddl: false
    hibernate:
      ddl-auto: none
    show-sql: true

mongock:
  migration-scan-package:
    - ru.otus.hw.migration
  enabled: true
  transactional: false
  runner-type: initializingbean
  mongo-db:
    write-concern:
      journal: false
    read-concern: local

logging:
  level:
    ROOT: info
    org:
      springframework:
        data:
          mongodb:
            core:
              MongoTemplate: DEBUG
    Batch: INFO
