spring:
  data:
    mongodb:
      host: localhost
      database: book_db
  shell:
    interactive:
      enabled: true
    noninteractive:
      enabled: false
    command:
      version:
        enabled: false
mongock:
  migration-scan-package:
    - ru.otus.hw.migration
  enabled: true
  transactional: false
  runner-type: initializingbean
  mongo-db:
    write-concern:
      journal: false
    read-concern: local

logging:
  level:
    ROOT: info
    org:
      springframework:
        data:
          mongodb:
            core:
              MongoTemplate: DEBUG